from app.main import app


def test_required_route_contract_is_registered():
    routes = {(method, route.path) for route in app.routes for method in getattr(route, "methods", set())}
    required = {
        ("POST", "/api/v1/auth/login"),
        ("POST", "/api/v1/auth/register"),
        ("GET", "/api/v1/auth/me"),
        ("POST", "/api/v1/seller/application"),
        ("GET", "/api/v1/seller/me"),
        ("GET", "/api/v1/admin/sellers"),
        ("PATCH", "/api/v1/admin/sellers/{seller_id}/decision"),
        ("GET", "/api/v1/metadata/fields"),
        ("GET", "/api/v1/products"),
        ("GET", "/api/v1/products/{slug_or_id}"),
        ("POST", "/api/v1/product-drafts"),
        ("GET", "/api/v1/managed-products"),
        ("GET", "/api/v1/product-drafts/options"),
        ("POST", "/api/v1/ai-processing/reserve"),
        ("POST", "/api/v1/ai-processing/{run_id}/complete"),
        ("POST", "/api/v1/ai-processing/{run_id}/fail"),
        ("GET", "/api/v1/home"),
        ("GET", "/api/v1/dashboard/stats"),
        ("GET", "/api/v1/filters"),
        ("GET", "/api/v1/profile"),
        ("PATCH", "/api/v1/profile"),
        ("POST", "/api/v1/profile/onboarding/complete"),
        ("POST", "/api/v1/profile/appearance/reserve"),
        ("GET", "/api/v1/orders"),
        ("GET", "/api/v1/cart"),
        ("POST", "/api/v1/cart/items"),
        ("POST", "/api/v1/search/parse"),
        ("POST", "/api/v1/search/advanced"),
        ("POST", "/api/v1/locations/resolve-pincode"),
        ("GET", "/api/v1/products/{slug_or_id}/related"),
        ("POST", "/api/v1/internal/taxonomy-reconciler/search-outcome"),
        ("POST", "/api/v1/public/taxonomy-reconciler/run"),
        ("GET", "/api/v1/public/taxonomy-reconciler/run"),
        ("POST", "/api/v1/admin/taxonomy-reconciler/run"),
        ("GET", "/api/v1/admin/taxonomy-reconciler/queries"),
        ("GET", "/api/v1/admin/taxonomy-reconciler/runs"),
        ("GET", "/api/v1/admin/taxonomy-reconciler/proposals"),
        ("PATCH", "/api/v1/admin/taxonomy-reconciler/proposals/{proposal_id}/decision"),
        ("POST", "/api/v1/admin/taxonomy-reconciler/proposals/apply"),
        ("GET", "/api/v1/admin/taxonomy-reconciler/graph"),
        ("POST", "/api/v1/admin/taxonomy-reconciler/graph/preview"),
    }
    assert required <= routes
