"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Bot, Braces, CheckCircle2, CircleDotDashed, FlaskConical, GitBranch, KeyRound, Layers3, LoaderCircle, Megaphone, PhoneCall, Plus, RefreshCw, Save, Search, ShieldCheck, Sparkles, UsersRound, Wrench, X, XCircle } from "lucide-react";

import SwarmDagStudio from "@/components/admin/agents/SwarmDagStudio";
import SarvamVoicePicker from "@/components/admin/agents/SarvamVoicePicker";
import { getCampaignAnalytics, getCalls, loadAgentWorkspace, saveAgent, saveCampaign, saveProviderCredential, saveSwarm, scheduleCampaign, triggerTestCall } from "@/lib/api/agent-admin";
import type { AgentConfig, AgentSwarm, AgentToolDefinition, AiCall, AiCampaign, ProviderCredentialStatus } from "@/types/ai-agents";

type Tab = "agents" | "swarms" | "campaigns" | "test" | "calls" | "credentials";
type Workspace = { agents: AgentConfig[]; tools: AgentToolDefinition[]; swarms: AgentSwarm[]; campaigns: AiCampaign[]; calls: AiCall[]; callsTotal: number; credentials: ProviderCredentialStatus[] };

const tabs: Array<{ key: Tab; label: string; icon: typeof Bot }> = [
  { key: "agents", label: "Agents", icon: Bot }, { key: "swarms", label: "Swarms & DAG", icon: GitBranch }, { key: "campaigns", label: "Campaigns", icon: Megaphone }, { key: "test", label: "Test call", icon: FlaskConical }, { key: "calls", label: "All calls", icon: PhoneCall }, { key: "credentials", label: "API keys", icon: KeyRound },
];

const bulbulLanguages = [
  ["en-IN", "English (India)"], ["hi-IN", "Hindi"], ["bn-IN", "Bengali"],
  ["ta-IN", "Tamil"], ["te-IN", "Telugu"], ["gu-IN", "Gujarati"],
  ["kn-IN", "Kannada"], ["ml-IN", "Malayalam"], ["mr-IN", "Marathi"],
  ["pa-IN", "Punjabi"], ["od-IN", "Odia"],
] as const;

export default function AgentsPage() {
  const [workspace, setWorkspace] = useState<Workspace>({ agents: [], tools: [], swarms: [], campaigns: [], calls: [], callsTotal: 0, credentials: [] });
  const [tab, setTab] = useState<Tab>("agents");
  const [createForSwarm, setCreateForSwarm] = useState<{ swarmId: string; fromNodeKey: string } | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  async function refresh() {
    setLoading(true); setError("");
    try { setWorkspace(await loadAgentWorkspace()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Agent workspace could not be loaded."); } finally { setLoading(false); }
  }
  useEffect(() => {
    let cancelled = false;
    void loadAgentWorkspace()
      .then((next) => {
        if (!cancelled) setWorkspace(next);
      })
      .catch((reason: unknown) => {
        if (!cancelled) setError(reason instanceof Error ? reason.message : "Agent workspace could not be loaded.");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => { cancelled = true; };
  }, []);

  async function finishAgentSave(saved: AgentConfig) {
    const target = workspace.swarms.find((swarm) => swarm.id === createForSwarm?.swarmId);
    if (target && !target.graph.nodes.some((node) => node.agentId === saved.id)) {
      const baseKey = (saved.key || "agent").toLowerCase().replace(/[^a-z0-9_]+/g, "_").replace(/^_+|_+$/g, "") || "agent";
      let key = baseKey;
      let suffix = 2;
      while (target.graph.nodes.some((node) => node.key === key)) key = `${baseKey}_${suffix++}`;
      const fromNode = target.graph.nodes.find((node) => node.key === createForSwarm?.fromNodeKey) ?? target.graph.nodes.find((node) => node.key === target.graph.entryNodeKey);
      const sourceAgent = workspace.agents.find((agent) => agent.id === fromNode?.agentId);
      if (sourceAgent && !sourceAgent.tools.some((tool) => tool.key === "handoff" && tool.enabled)) {
        const definition = workspace.tools.find((tool) => tool.key === "handoff");
        const configured = sourceAgent.tools.find((tool) => tool.key === "handoff");
        await saveAgent({ ...sourceAgent, tools: configured ? sourceAgent.tools.map((tool) => tool.key === "handoff" ? { ...tool, enabled: true } : tool) : [...sourceAgent.tools, { key: "handoff", description: definition?.description ?? "Move a conversation through a matching swarm edge.", enabled: true }] });
      }
      const edges = fromNode ? [...target.graph.edges, { from: fromNode.key, to: key, priority: 10, condition: { field: "handoff_route", operator: "eq", value: key }, handoffMessage: `I'll connect you with ${saved.name}.` }] : target.graph.edges;
      await saveSwarm({ ...target, graph: { ...target.graph, nodes: [...target.graph.nodes, { key, agentId: saved.id, instructionOverrides: "", metadata: {} }], edges } });
      setCreateForSwarm(null);
      setTab("swarms");
    }
    await refresh();
  }

  return <div className="min-h-full bg-[#fffafa] p-4 sm:p-6 lg:p-8">
    <header className="mx-auto flex max-w-[90rem] flex-wrap items-end justify-between gap-4"><div><span className="inline-flex items-center gap-1.5 rounded-full bg-pink-100 px-3 py-1 text-[10px] font-black uppercase tracking-[0.14em] text-pink-700"><Sparkles className="size-3" /> StylMe intelligence</span><h1 className="mt-3 text-3xl font-black tracking-[-0.04em] text-zinc-950 sm:text-4xl">Agent Studio</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">Configure web and voice instructions, compose safe handoff DAGs, launch outbound campaigns, and inspect inbound and outbound calls in one place.</p></div><button type="button" onClick={() => void refresh()} disabled={loading} className="inline-flex h-10 items-center gap-2 rounded-xl border border-zinc-200 bg-white px-4 text-xs font-black text-zinc-700 shadow-sm"><RefreshCw className={`size-4 ${loading ? "animate-spin" : ""}`} /> Refresh</button></header>

    <div className="mx-auto mt-7 max-w-[90rem] rounded-2xl border border-pink-100 bg-white p-1.5 shadow-[0_18px_60px_-45px_rgba(190,24,93,0.5)]"><nav className="grid grid-cols-2 gap-1 lg:grid-cols-6">{tabs.map((item) => { const Icon = item.icon; return <button key={item.key} type="button" onClick={() => setTab(item.key)} className={`flex items-center justify-center gap-2 rounded-xl px-3 py-2.5 text-xs font-black transition ${tab === item.key ? "bg-zinc-950 text-white" : "text-zinc-500 hover:bg-pink-50 hover:text-pink-700"}`}><Icon className="size-4" />{item.label}</button>; })}</nav></div>

    <main className="mx-auto mt-5 max-w-[90rem]">{error && <div className="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}{loading ? <div className="grid min-h-80 place-items-center rounded-3xl border border-pink-100 bg-white"><div className="text-center"><LoaderCircle className="mx-auto size-6 animate-spin text-pink-600" /><p className="mt-3 text-sm text-zinc-500">Loading the agent graph…</p></div></div> : <>
      {tab === "agents" && <AgentsPanel agents={workspace.agents} tools={workspace.tools} createTarget={workspace.swarms.find((swarm) => swarm.id === createForSwarm?.swarmId) ?? null} onSaved={finishAgentSave} onCancelCreate={() => setCreateForSwarm(null)} />}
      {tab === "swarms" && <SwarmsPanel swarms={workspace.swarms} agents={workspace.agents} tools={workspace.tools} onSaved={refresh} onCreateAgent={(swarmId, fromNodeKey) => { setCreateForSwarm({ swarmId, fromNodeKey }); setTab("agents"); }} />}
      {tab === "campaigns" && <CampaignsPanel campaigns={workspace.campaigns} swarms={workspace.swarms} onSaved={refresh} />}
      {tab === "test" && <TestCallPanel swarms={workspace.swarms} agents={workspace.agents} />}
      {tab === "calls" && <CallsPanel calls={workspace.calls} totalCount={workspace.callsTotal} agents={workspace.agents} />}
      {tab === "credentials" && <CredentialsPanel credentials={workspace.credentials} onSaved={refresh} />}
    </>}</main>
  </div>;
}

function newAgentDraft(target: AgentSwarm | null): AgentConfig {
  const channel = target?.channels[0] ?? "voice";
  const direction = target?.directions[0] ?? (channel === "web" ? "interactive" : "inbound");
  return {
    id: "", key: "", name: "Untitled agent", description: "A focused reusable agent role.", channels: [channel], direction, status: "draft", isDefault: false, revision: 0,
    instructions: { system: "Describe this agent's role, boundaries, allowed facts, and handoff behavior.", greeting: "", guardrails: ["Never invent operational facts; use an enabled tool or a verified fallback."], fallback: "I cannot verify that safely, so I can route this request to the next supported path.", },
    model: { provider: "openai", name: "gpt-5.6-luna", temperature: 0.2, maxOutputTokens: 900, reasoningEffort: "none" },
    voice: channel === "voice" ? { language: "multi", sttProvider: "deepgram", sttModel: "nova-3", ttsProvider: "sarvam", ttsModel: "bulbul:v3", speaker: "shubh", pace: 1, allowInterruption: true, endCallAfterSec: 900 } : undefined,
    web: channel === "web" ? { starterPrompts: [], maxHistoryMessages: 12, resultLimit: 8, allowProfileProposal: false } : undefined,
    tools: channel === "web" ? [{ key: "search_catalog", description: "Search real products before stating catalogue facts.", enabled: true }] : [], capture: { fields: [] }, metadata: {},
  };
}

function AgentsPanel({ agents, tools, createTarget, onSaved, onCancelCreate }: { agents: AgentConfig[]; tools: AgentToolDefinition[]; createTarget: AgentSwarm | null; onSaved: (agent: AgentConfig) => Promise<void>; onCancelCreate: () => void }) {
  const [selectedId, setSelectedId] = useState(agents[0]?.id ?? "");
  const [creating, setCreating] = useState(Boolean(createTarget));
  const selected = creating ? newAgentDraft(createTarget) : agents.find((agent) => agent.id === selectedId) ?? agents[0] ?? null;
  return <div className="grid gap-5 xl:grid-cols-[18rem_minmax(0,1fr)] 2xl:grid-cols-[18rem_minmax(0,1fr)_20rem]">
    <section className="rounded-3xl border border-pink-100 bg-white p-3"><button type="button" onClick={() => { setCreating(true); setSelectedId(""); }} className="mb-3 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-zinc-950 text-xs font-black text-white"><Plus className="size-4" /> New reusable agent</button><div className="flex items-center justify-between px-2 py-2"><div><h2 className="text-sm font-black">Configured agents</h2><p className="text-[10px] text-zinc-400">Revisioned runtime records.</p></div><span className="rounded-full bg-pink-50 px-2.5 py-1 text-[10px] font-black text-pink-700">{agents.length}</span></div><div className="mt-2 space-y-2">{agents.map((agent) => <button key={agent.id} type="button" onClick={() => { setSelectedId(agent.id); setCreating(false); onCancelCreate(); }} className={`w-full rounded-2xl border p-4 text-left transition ${!creating && selected?.id === agent.id ? "border-pink-300 bg-pink-50" : "border-zinc-100 hover:border-pink-200"}`}><div className="flex items-start justify-between gap-2"><span className="grid size-9 place-items-center rounded-xl bg-zinc-950 text-white"><Bot className="size-4" /></span><StatusBadge value={agent.status} /></div><p className="mt-3 text-sm font-black text-zinc-950">{agent.name}</p><p className="mt-1 line-clamp-2 text-[11px] leading-5 text-zinc-500">{agent.description}</p><div className="mt-3 flex flex-wrap gap-1">{agent.channels.map((channel) => <span key={channel} className="rounded-full bg-white px-2 py-0.5 text-[9px] font-black uppercase text-zinc-500">{channel}</span>)}<span className="rounded-full bg-white px-2 py-0.5 text-[9px] font-black uppercase text-zinc-500">{agent.tools.filter((tool) => tool.enabled).length} tools</span><span className="rounded-full bg-white px-2 py-0.5 text-[9px] font-black uppercase text-zinc-500">rev {agent.revision}</span>{agent.isDefault && <span className="rounded-full bg-pink-600 px-2 py-0.5 text-[9px] font-black uppercase text-white">default</span>}</div></button>)}</div></section>
    {selected ? <AgentEditor key={selected.id ? `${selected.id}-${selected.revision}` : `new-${createTarget?.id ?? "standalone"}`} source={selected} tools={tools} createTarget={createTarget} onSaved={onSaved} onCancel={() => { setCreating(false); onCancelCreate(); }} /> : <EmptyState title="Create your first agent" />}
    <ToolLibraryPanel tools={tools} />
  </div>;
}

function AgentEditor({ source, tools, createTarget, onSaved, onCancel }: { source: AgentConfig; tools: AgentToolDefinition[]; createTarget: AgentSwarm | null; onSaved: (agent: AgentConfig) => Promise<void>; onCancel: () => void }) {
  const [value, setValue] = useState(() => structuredClone(source));
  const [saving, setSaving] = useState(false); const [notice, setNotice] = useState("");
  function patch<K extends keyof AgentConfig>(key: K, next: AgentConfig[K]) { setValue((current) => ({ ...current, [key]: next })); }
  function changeChannel(channel: string) { setValue((current) => { const hasSearch = current.tools.some((tool) => tool.key === "search_catalog"); const nextTools = channel === "web" ? hasSearch ? current.tools.map((tool) => tool.key === "search_catalog" ? { ...tool, enabled: true } : tool) : [...current.tools, { key: "search_catalog", description: "Search real products before stating catalogue facts.", enabled: true }] : current.tools; return { ...current, channels: [channel], direction: channel === "web" ? "interactive" : current.direction === "interactive" ? "inbound" : current.direction, voice: channel === "voice" ? current.voice ?? newAgentDraft(null).voice : current.voice, web: channel === "web" ? current.web ?? newAgentDraft({ channels: ["web"], directions: ["interactive"] } as AgentSwarm).web : current.web, tools: nextTools }; }); }
  async function commit() { setSaving(true); setNotice(""); try { const next = { ...value, key: value.key.trim().toLowerCase().replace(/[^a-z0-9_-]+/g, "-") }; const saved = await saveAgent(next); setNotice(source.id ? "Saved as a new revision." : "Agent created."); await onSaved(saved); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Save failed."); } finally { setSaving(false); } }
  return <section className="min-w-0 rounded-3xl border border-pink-100 bg-white p-5 sm:p-7">{createTarget && <div className="mb-6 flex items-start gap-3 rounded-2xl border border-violet-200 bg-violet-50 p-4"><Layers3 className="mt-0.5 size-4 shrink-0 text-violet-700" /><div className="flex-1"><p className="text-xs font-black text-violet-950">Create and attach to {createTarget.name}</p><p className="mt-1 text-[10px] leading-4 text-violet-700">After the first save, this becomes a routed node. The source node&apos;s handoff tool is enabled if needed.</p></div><button type="button" onClick={onCancel} aria-label="Cancel create flow"><X className="size-4 text-violet-600" /></button></div>}<div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.14em] text-pink-600">{source.id ? "Agent configuration" : "New agent"}</p><h2 className="mt-1 text-2xl font-black tracking-tight text-zinc-950">{value.name}</h2><p className="mt-1 font-mono text-[10px] text-zinc-400">{value.key || "agent-key-required"} · {source.id ? `revision ${value.revision}` : "unsaved"}</p></div><label className="flex items-center gap-2 rounded-xl bg-pink-50 px-3 py-2 text-xs font-black text-pink-800"><input type="checkbox" checked={value.isDefault} onChange={(event) => patch("isDefault", event.target.checked)} className="accent-pink-600" /> Default for this route</label></div>
    <div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Name"><input value={value.name} onChange={(event) => patch("name", event.target.value)} className={inputClass} /></Field><Field label="Agent key"><input value={value.key} onChange={(event) => patch("key", event.target.value)} placeholder="order-support-specialist" className={inputClass} /></Field><Field label="Status"><select value={value.status} onChange={(event) => patch("status", event.target.value)} className={inputClass}><option value="draft">Draft</option><option value="active">Active</option><option value="paused">Paused</option><option value="archived">Archived</option></select></Field><Field label="Description"><input value={value.description} onChange={(event) => patch("description", event.target.value)} className={inputClass} /></Field></div>
    <SectionTitle title="Channel & runtime" note="Tool availability and swarm compatibility are enforced from these settings." /><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Field label="Channel"><select value={value.channels[0] ?? "voice"} onChange={(event) => changeChannel(event.target.value)} disabled={Boolean(createTarget)} className={inputClass}><option value="voice">Voice</option><option value="web">Web</option></select></Field><Field label="Direction"><select value={value.direction} onChange={(event) => patch("direction", event.target.value)} disabled={Boolean(createTarget)} className={inputClass}>{value.channels.includes("web") ? <option value="interactive">Interactive</option> : <><option value="inbound">Inbound</option><option value="outbound">Outbound</option></>}</select></Field><Field label="Model"><input value={value.model.name} onChange={(event) => patch("model", { ...value.model, name: event.target.value })} className={inputClass} /></Field><Field label="Reasoning"><select value={value.model.reasoningEffort ?? "none"} onChange={(event) => patch("model", { ...value.model, reasoningEffort: event.target.value })} className={inputClass}><option>none</option><option>low</option><option>medium</option></select></Field><Field label="Temperature"><input type="number" min={0} max={2} step={0.1} value={value.model.temperature} onChange={(event) => patch("model", { ...value.model, temperature: Number(event.target.value) })} className={inputClass} /></Field><Field label="Max output"><input type="number" min={100} max={4000} value={value.model.maxOutputTokens} onChange={(event) => patch("model", { ...value.model, maxOutputTokens: Number(event.target.value) })} className={inputClass} /></Field></div>
    <SectionTitle title="Instructions" note="These are runtime instructions, not frontend copy." /><div className="grid gap-5"><Field label="System instructions"><textarea rows={8} value={value.instructions.system} onChange={(event) => patch("instructions", { ...value.instructions, system: event.target.value })} className={textareaClass} /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Greeting"><textarea rows={3} value={value.instructions.greeting} onChange={(event) => patch("instructions", { ...value.instructions, greeting: event.target.value })} className={textareaClass} /></Field><Field label="Verified fallback"><textarea rows={3} value={value.instructions.fallback} onChange={(event) => patch("instructions", { ...value.instructions, fallback: event.target.value })} className={textareaClass} /></Field></div><Field label="Guardrails · one per line"><textarea rows={5} value={value.instructions.guardrails.join("\n")} onChange={(event) => patch("instructions", { ...value.instructions, guardrails: event.target.value.split("\n").map((item) => item.trim()).filter(Boolean) })} className={textareaClass} /></Field></div>
    {value.channels.includes("voice") && value.voice && <><SectionTitle title="Voice" note="Deepgram handles STT; Sarvam Bulbul v3 handles speech output." /><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Field label="Deepgram model"><input value={value.voice.sttModel} onChange={(event) => patch("voice", { ...value.voice!, sttModel: event.target.value })} className={inputClass} /></Field><Field label="Voice runtime"><div className={`${inputClass} flex items-center justify-between bg-zinc-50`}><span className="font-bold text-zinc-700">Sarvam Bulbul v3</span><span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[9px] font-black uppercase text-emerald-700">Validated</span></div></Field><Field label="Maximum call seconds"><input type="number" min={30} max={3600} value={value.voice.endCallAfterSec} onChange={(event) => patch("voice", { ...value.voice!, endCallAfterSec: Number(event.target.value) })} className={inputClass} /></Field><Field label="Caller interruptions"><button type="button" onClick={() => patch("voice", { ...value.voice!, allowInterruption: !value.voice!.allowInterruption })} className={`h-11 w-full rounded-xl border text-xs font-black ${value.voice.allowInterruption ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-zinc-200 text-zinc-500"}`}>{value.voice.allowInterruption ? "Allowed" : "Blocked"}</button></Field></div><SarvamVoicePicker value={value.voice} onChange={(next) => patch("voice", next)} /></>}
    {value.channels.includes("web") && value.web && <><SectionTitle title="Web behavior" note="Control shopper starters, context size, result density, and profile proposals." /><div className="grid gap-5 sm:grid-cols-2"><Field label="Starter prompts · one per line" wide><textarea rows={5} value={value.web.starterPrompts.join("\n")} onChange={(event) => patch("web", { ...value.web!, starterPrompts: event.target.value.split("\n").map((item) => item.trim()).filter(Boolean) })} className={textareaClass} /></Field><Field label="History messages"><input type="number" min={1} max={50} value={value.web.maxHistoryMessages} onChange={(event) => patch("web", { ...value.web!, maxHistoryMessages: Number(event.target.value) })} className={inputClass} /></Field><Field label="Result limit"><input type="number" min={1} max={50} value={value.web.resultLimit} onChange={(event) => patch("web", { ...value.web!, resultLimit: Number(event.target.value) })} className={inputClass} /></Field><label className="flex items-center gap-3 rounded-xl border border-zinc-200 px-4 text-xs font-black text-zinc-700 sm:col-span-2"><input type="checkbox" checked={value.web.allowProfileProposal} onChange={(event) => patch("web", { ...value.web!, allowProfileProposal: event.target.checked })} className="size-4 accent-pink-600" /> Allow confirmed profile-update proposals</label></div></>}
    <SectionTitle title="Tools" note="Choose only catalog capabilities compatible with this channel and direction." /><ToolAssignmentPanel value={value} tools={tools} onChange={(next) => patch("tools", next)} />
    <SectionTitle title="Disposition contract" note="Define the exact explicit fields this agent may capture and summarize." /><CaptureContractEditor fields={value.capture.fields} onChange={(fields) => patch("capture", { fields })} />
    <div className="mt-7 flex items-center justify-end gap-3">{notice && <p role="status" className={`mr-auto text-xs font-semibold ${notice.startsWith("Saved") || notice.startsWith("Agent created") ? "text-emerald-700" : "text-red-700"}`}>{notice}</p>}{!source.id && <button type="button" onClick={onCancel} className="h-11 rounded-xl border border-zinc-200 px-5 text-xs font-black text-zinc-600">Cancel</button>}<button type="button" onClick={() => void commit()} disabled={saving || !value.name.trim() || !value.key.trim()} className="inline-flex h-11 items-center gap-2 rounded-xl bg-pink-600 px-5 text-xs font-black text-white shadow-lg shadow-pink-200 disabled:opacity-50">{saving ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />} {source.id ? "Save revision" : createTarget ? "Create & attach" : "Create agent"}</button></div>
  </section>;
}

function ToolAssignmentPanel({ value, tools, onChange }: { value: AgentConfig; tools: AgentToolDefinition[]; onChange: (tools: AgentConfig["tools"]) => void }) {
  const visible = tools.filter((tool) => tool.channels.some((channel) => value.channels.includes(channel)) && (tool.directions.length === 0 || tool.directions.includes(value.direction)) || value.tools.some((configured) => configured.key === tool.key));
  const groups = [...new Set(visible.map((tool) => tool.group))];
  function toggle(definition: AgentToolDefinition) { const current = value.tools.find((tool) => tool.key === definition.key); if (current) onChange(value.tools.map((tool) => tool.key === definition.key ? { ...tool, enabled: !tool.enabled } : tool)); else onChange([...value.tools, { key: definition.key, description: definition.description, enabled: true }]); }
  return <div className="space-y-5">{groups.map((group) => <div key={group}><div className="mb-2 flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.12em] text-zinc-400"><Wrench className="size-3" /> {group}</div><div className="grid gap-2 lg:grid-cols-2">{visible.filter((tool) => tool.group === group).map((tool) => { const configured = value.tools.find((item) => item.key === tool.key); const requiredByRuntime = value.channels.includes("web") && tool.key === "search_catalog"; const checked = requiredByRuntime || tool.availability === "always_on" || Boolean(configured?.enabled); const blocked = !tool.assignable && !checked; return <label key={tool.key} className={`flex gap-3 rounded-2xl border p-3.5 transition ${checked ? "border-pink-300 bg-pink-50/70" : blocked ? "border-zinc-100 bg-zinc-50 opacity-70" : "border-zinc-200 hover:border-pink-200"}`}><input type="checkbox" checked={checked} disabled={requiredByRuntime || tool.availability === "always_on" || blocked} onChange={() => toggle(tool)} className="mt-1 size-4 accent-pink-600" /><span className="min-w-0 flex-1"><span className="flex items-start justify-between gap-2"><span className="text-xs font-black text-zinc-900">{tool.name}</span><ToolAvailability value={tool.availability} /></span><span className="mt-1 block text-[10px] leading-4 text-zinc-500">{tool.description}</span>{requiredByRuntime && <span className="mt-2 block text-[9px] font-semibold leading-4 text-pink-700">Required by the web reply runtime.</span>}{tool.requirements[0] && <span className="mt-2 block text-[9px] font-semibold leading-4 text-amber-700">{tool.requirements[0]}</span>}</span></label>; })}</div></div>)}{!visible.length && <p className="rounded-2xl border border-dashed border-zinc-200 p-5 text-xs text-zinc-500">No registered tools match this channel and direction.</p>}</div>;
}

function CaptureContractEditor({ fields, onChange }: { fields: AgentConfig["capture"]["fields"]; onChange: (fields: AgentConfig["capture"]["fields"]) => void }) {
  function patchField(index: number, patch: Partial<AgentConfig["capture"]["fields"][number]>) { onChange(fields.map((field, fieldIndex) => fieldIndex === index ? { ...field, ...patch } : field)); }
  function addField() { let index = fields.length + 1; while (fields.some((field) => field.key === `field_${index}`)) index += 1; onChange([...fields, { key: `field_${index}`, label: "New field", type: "string", description: "Capture only when the user states this explicitly.", required: false }]); }
  return <div><div className="space-y-3">{fields.map((field, index) => <div key={`${field.key}-${index}`} className="rounded-2xl border border-zinc-200 bg-zinc-50/50 p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-[1fr_1.25fr_0.8fr_auto]"><Field label="Field key"><input value={field.key} onChange={(event) => patchField(index, { key: event.target.value.toLowerCase().replace(/[^a-z0-9_]+/g, "_") })} className={inputClass} /></Field><Field label="Label"><input value={field.label} onChange={(event) => patchField(index, { label: event.target.value })} className={inputClass} /></Field><Field label="Type"><select value={field.type} onChange={(event) => patchField(index, { type: event.target.value })} className={inputClass}><option value="string">Text</option><option value="boolean">Yes / no</option><option value="number">Number</option><option value="number_range">Number range</option><option value="datetime">Date & time</option><option value="select">Single select</option><option value="multi_select">Multi-select</option></select></Field><button type="button" onClick={() => onChange(fields.filter((_, fieldIndex) => fieldIndex !== index))} aria-label={`Remove ${field.label}`} className="mt-[1.15rem] grid size-11 place-items-center rounded-xl border border-red-100 bg-white text-red-600"><X className="size-4" /></button></div><div className="mt-3 grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><Field label="Description"><input value={field.description} onChange={(event) => patchField(index, { description: event.target.value })} className={inputClass} /></Field><label className="flex h-11 items-center gap-2 self-end rounded-xl border border-zinc-200 bg-white px-3 text-[10px] font-black text-zinc-700"><input type="checkbox" checked={field.required} onChange={(event) => patchField(index, { required: event.target.checked })} className="size-4 accent-pink-600" /> Required</label></div>{["select", "multi_select"].includes(field.type) && <div className="mt-3"><Field label="Allowed values · comma separated"><input value={(field.enum ?? []).join(", ")} onChange={(event) => patchField(index, { enum: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} className={inputClass} /></Field></div>}</div>)}{!fields.length && <div className="rounded-2xl border border-dashed border-zinc-200 p-6 text-center"><CircleDotDashed className="mx-auto size-5 text-zinc-300" /><p className="mt-2 text-xs font-black text-zinc-700">No disposition fields</p><p className="mt-1 text-[10px] text-zinc-400">The agent will not collect structured answers.</p></div>}</div><button type="button" onClick={addField} className="mt-3 inline-flex h-10 items-center gap-2 rounded-xl border border-pink-200 bg-pink-50 px-4 text-[10px] font-black text-pink-700"><Plus className="size-3.5" /> Add capture field</button></div>;
}

function ToolAvailability({ value }: { value: AgentToolDefinition["availability"] }) { const style = value === "ready" ? "bg-emerald-50 text-emerald-700" : value === "setup_required" ? "bg-amber-50 text-amber-700" : value === "always_on" ? "bg-violet-50 text-violet-700" : "bg-zinc-100 text-zinc-500"; return <span className={`shrink-0 rounded-full px-2 py-1 text-[8px] font-black uppercase ${style}`}>{value.replaceAll("_", " ")}</span>; }

function ToolLibraryPanel({ tools }: { tools: AgentToolDefinition[] }) {
  const [query, setQuery] = useState("");
  const filtered = tools.filter((tool) => `${tool.name} ${tool.key} ${tool.group}`.toLowerCase().includes(query.trim().toLowerCase()));
  const availability = ["ready", "setup_required", "always_on", "unavailable"] as const;
  return <aside className="self-start rounded-3xl border border-violet-100 bg-white p-4 xl:col-span-2 2xl:sticky 2xl:top-5 2xl:col-span-1 2xl:max-h-[calc(100vh-2.5rem)] 2xl:overflow-y-auto"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-violet-600 text-white"><Wrench className="size-4" /></span><div><h2 className="text-sm font-black text-zinc-950">Internal tool library</h2><p className="mt-1 text-[10px] leading-4 text-zinc-500">Authoritative runtime capabilities, grouped by availability.</p></div></div><label className="relative mt-4 block"><Search className="absolute left-3 top-3 size-3.5 text-zinc-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search tools" className={`${inputClass} pl-9`} /></label><div className="mt-5 space-y-5">{availability.map((status) => { const items = filtered.filter((tool) => tool.availability === status); if (!items.length) return null; return <section key={status}><div className="mb-2 flex items-center justify-between"><ToolAvailability value={status} /><span className="text-[9px] font-black text-zinc-400">{items.length}</span></div><div className="space-y-2">{items.map((tool) => <div key={tool.key} className="rounded-2xl border border-zinc-100 p-3"><div className="flex items-start justify-between gap-2"><p className="text-[11px] font-black text-zinc-900">{tool.name}</p><span className="rounded-full bg-zinc-50 px-2 py-0.5 text-[8px] font-black uppercase text-zinc-500">{tool.group}</span></div><p className="mt-1.5 text-[9px] leading-4 text-zinc-500">{tool.description}</p><div className="mt-2 flex flex-wrap gap-1">{tool.channels.map((channel) => <span key={channel} className="rounded-full bg-violet-50 px-2 py-0.5 text-[8px] font-black uppercase text-violet-700">{channel}</span>)}<span className="rounded-full bg-zinc-50 px-2 py-0.5 text-[8px] font-mono text-zinc-500">{tool.key}</span></div></div>)}</div></section>; })}</div></aside>;
}

function newSwarmDraft(agents: AgentConfig[]): AgentSwarm | null {
  const agent = agents.find((item) => item.status === "active") ?? agents[0];
  if (!agent) return null;
  const channel = agent.channels[0] ?? "voice";
  return { id: "", key: `workflow-${Date.now()}`, name: "New agent workflow", description: "A reusable, versioned agent handoff workflow.", channels: [channel], directions: [agent.direction], status: "draft", isDefault: false, revision: 0, graph: { entryNodeKey: "agent_1", nodes: [{ key: "agent_1", agentId: agent.id, instructionOverrides: "", metadata: {} }], edges: [] }, telephony: {}, metadata: {} };
}

function SwarmsPanel({ swarms, agents, tools, onSaved, onCreateAgent }: { swarms: AgentSwarm[]; agents: AgentConfig[]; tools: AgentToolDefinition[]; onSaved: () => Promise<void>; onCreateAgent: (swarmId: string, fromNodeKey: string) => void }) {
  const [selectedId, setSelectedId] = useState(swarms[0]?.id ?? "");
  const [draft, setDraft] = useState<AgentSwarm | null>(null);
  const selected = draft ?? swarms.find((swarm) => swarm.id === selectedId) ?? swarms[0] ?? null;
  return <div className="grid gap-5 2xl:grid-cols-[17rem_minmax(0,1fr)]"><section className="rounded-3xl border border-pink-100 bg-white p-3"><button type="button" onClick={() => { setDraft(newSwarmDraft(agents)); setSelectedId(""); }} disabled={!agents.length} className="mb-3 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-zinc-950 text-xs font-black text-white disabled:opacity-40"><Plus className="size-4" /> New workflow</button><div className="px-2 py-2"><h2 className="text-sm font-black">Agent workflows</h2><p className="text-[10px] leading-4 text-zinc-400">Versioned DAGs for web, inbound, and outbound voice.</p></div><div className="mt-2 grid gap-2 sm:grid-cols-2 2xl:grid-cols-1">{swarms.map((swarm) => <button key={swarm.id} type="button" onClick={() => { setSelectedId(swarm.id); setDraft(null); }} className={`w-full rounded-2xl border p-4 text-left transition ${!draft && selected?.id === swarm.id ? "border-pink-300 bg-pink-50 shadow-sm" : "border-zinc-100 hover:border-pink-200"}`}><div className="flex items-center justify-between"><span className={`grid size-8 place-items-center rounded-xl ${!draft && selected?.id === swarm.id ? "bg-pink-600 text-white" : "bg-zinc-950 text-white"}`}><GitBranch className="size-4" /></span><StatusBadge value={swarm.status} /></div><p className="mt-3 text-sm font-black">{swarm.name}</p><p className="mt-1 line-clamp-2 text-[10px] leading-4 text-zinc-500">{swarm.description || "Reusable agent workflow"}</p><div className="mt-3 flex items-center gap-2 text-[9px] font-black uppercase text-zinc-400"><span>{swarm.graph.nodes.length} agents</span><span>•</span><span>{swarm.graph.edges.length} routes</span><span>•</span><span>rev {swarm.revision}</span></div></button>)}</div></section>{selected ? <SwarmDagStudio key={selected.id ? `${selected.id}-${selected.revision}` : selected.key} source={selected} agents={agents} tools={tools} onSaved={onSaved} onCreateAgent={(fromNodeKey) => selected.id && onCreateAgent(selected.id, fromNodeKey)} /> : <EmptyState title="Create your first workflow" />}</div>;
}

function CampaignsPanel({ campaigns, swarms, onSaved }: { campaigns: AiCampaign[]; swarms: AgentSwarm[]; onSaved: () => Promise<void> }) {
  const [selectedId, setSelectedId] = useState(campaigns[0]?.id ?? "");
  const selected = campaigns.find((campaign) => campaign.id === selectedId) ?? campaigns[0] ?? null;
  async function createNew() { const outbound = swarms.find((item) => item.directions.includes("outbound")); if (!outbound) return; const created = await saveCampaign({ id: "", name: "New outbound campaign", kind: "custom", swarmId: outbound.id, entryNodeKey: outbound.graph.entryNodeKey, status: "draft", direction: "outbound", fromNumber: outbound.telephony.phoneNumber ?? "", callingWindow: { timezone: "Asia/Kolkata", start: "10:00", end: "19:00" }, retryPolicy: { maxAttempts: 1, backoffMinutes: [5], retryOnCodes: ["no_answer", "busy"] }, maxConcurrency: 2, callsPerSecond: 1, language: "hi-IN", instructions: { objective: "Help the customer with this campaign purpose.", system: "Be concise, factual, consent-aware, and use only supplied context and tools.", greeting: "Hi, this is StylMe. Is now a good time for a quick chat?" }, capture: { fields: [{ key: "outcome", label: "Outcome", type: "string", description: "Explicit call outcome.", required: true }] }, counts: {}, metadata: {} }); setSelectedId(created.id); await onSaved(); }
  return <div className="grid gap-5 xl:grid-cols-[22rem_minmax(0,1fr)]"><section className="rounded-3xl border border-pink-100 bg-white p-3"><button onClick={() => void createNew()} className="mb-3 flex w-full items-center justify-center gap-2 rounded-xl bg-zinc-950 px-4 py-3 text-xs font-black text-white"><Plus className="size-4" /> New campaign</button>{campaigns.map((campaign) => <button key={campaign.id} onClick={() => setSelectedId(campaign.id)} className={`mb-2 w-full rounded-2xl border p-4 text-left ${selected?.id === campaign.id ? "border-pink-300 bg-pink-50" : "border-zinc-100"}`}><div className="flex justify-between"><Megaphone className="size-5 text-pink-600" /><StatusBadge value={campaign.status} /></div><p className="mt-3 text-sm font-black">{campaign.name}</p><p className="mt-1 text-[10px] text-zinc-500">{campaign.kind?.replaceAll("_", " ")} · starts at {campaign.entryNodeKey}</p><p className="mt-1 text-[10px] text-zinc-500">{campaign.counts?.scheduled ?? 0} scheduled · {campaign.counts?.completed ?? 0} completed</p></button>)}</section>{selected ? <CampaignEditor key={`${selected.id}-${selected.updatedAt ?? "current"}`} source={selected} swarms={swarms} onSaved={onSaved} /> : <EmptyState title="Create a campaign" />}</div>;
}

function CampaignEditor({ source, swarms, onSaved }: { source: AiCampaign; swarms: AgentSwarm[]; onSaved: () => Promise<void> }) {
  const [value, setValue] = useState(() => ({ ...structuredClone(source), kind: source.kind || "custom", entryNodeKey: source.entryNodeKey || swarms.find((item) => item.id === source.swarmId)?.graph.entryNodeKey || "", language: source.language || "hi-IN", instructions: source.instructions ?? { objective: "Help the customer with this campaign purpose.", system: "Be concise, factual, and consent-aware.", greeting: "Hi, this is StylMe. Is now a good time for a quick chat?" }, capture: source.capture ?? { fields: [] } })); const [capture, setCapture] = useState(() => JSON.stringify(source.capture?.fields ?? [], null, 2)); const [targets, setTargets] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [period, setPeriod] = useState<"day" | "month">("day"); const [analytics, setAnalytics] = useState<Array<{ period: string; status: string; count: number }>>([]);
  const swarm = swarms.find((item) => item.id === value.swarmId) ?? swarms[0];
  useEffect(() => { let active = true; void getCampaignAnalytics(source.id, period).then((result) => { if (active) setAnalytics(result.items); }).catch(() => { if (active) setAnalytics([]); }); return () => { active = false; }; }, [source.id, period]);
  async function commit() { setBusy(true); setNotice(""); try { await saveCampaign({ ...value, capture: { fields: JSON.parse(capture) } }); setNotice("Campaign instructions, start node, language, and questions saved."); await onSaved(); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Save failed."); } finally { setBusy(false); } }
  async function schedule() { setBusy(true); setNotice(""); try { const parsed = targets.split("\n").map((line) => line.trim()).filter(Boolean).map((line, index) => { const [phone, externalId, name] = line.split(",").map((item) => item.trim()); return { phone, externalId: externalId || `row-${index + 1}`, participant: name ? { name } : {}, context: {}, metadata: { source: "agent-studio", preferred_language: value.language } }; }); await scheduleCampaign(value.id, parsed); setNotice(`${parsed.length} target rows accepted idempotently.`); setTargets(""); await onSaved(); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Scheduling failed."); } finally { setBusy(false); } }
  function patch<K extends keyof AiCampaign>(key: K, next: AiCampaign[K]) { setValue((current) => ({ ...current, [key]: next })); }
  return <section className="rounded-3xl border border-pink-100 bg-white p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.14em] text-pink-600">Campaign runtime</p><h2 className="mt-1 text-2xl font-black">{value.name}</h2><p className="mt-1 text-xs text-zinc-500">The campaign chooses a DAG start node and overrides purpose—not the agent safety policy.</p></div><StatusBadge value={value.status} /></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric label="Scheduled" value={value.counts?.scheduled ?? 0} /><Metric label="Dispatched" value={value.counts?.dispatched ?? 0} /><Metric label="Completed" value={value.counts?.completed ?? 0} /></div>
    <SectionTitle title="Route & policy" note="One reusable agent can serve many campaigns; each call snapshots this configuration." /><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Field label="Campaign name"><input value={value.name} onChange={(event) => patch("name", event.target.value)} className={inputClass} /></Field><Field label="Workflow kind"><input value={value.kind} onChange={(event) => patch("kind", event.target.value)} className={inputClass} /></Field><Field label="Status"><select value={value.status} onChange={(event) => patch("status", event.target.value)} className={inputClass}><option value="draft">Draft</option><option value="running">Running</option><option value="paused">Paused</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></Field><Field label="Voice language"><select value={value.language} onChange={(event) => patch("language", event.target.value)} className={inputClass}>{bulbulLanguages.map(([code, label]) => <option key={code} value={code}>{label} · {code}</option>)}</select></Field><Field label="Swarm / DAG"><select value={value.swarmId} onChange={(event) => { const next = swarms.find((item) => item.id === event.target.value); setValue((current) => ({ ...current, swarmId: event.target.value, entryNodeKey: next?.graph.entryNodeKey ?? "", fromNumber: next?.telephony.phoneNumber ?? "" })); }} className={inputClass}>{swarms.filter((item) => item.directions.includes("outbound")).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Starts from agent node"><select value={value.entryNodeKey} onChange={(event) => patch("entryNodeKey", event.target.value)} className={inputClass}>{swarm?.graph.nodes.map((node) => <option key={node.key} value={node.key}>{node.key}</option>)}</select></Field><Field label="Managed caller ID"><ManagedPhoneNumber value={swarm?.telephony.phoneNumber} /></Field><Field label="Max active calls"><input type="number" min={1} max={50} value={value.maxConcurrency} onChange={(event) => patch("maxConcurrency", Number(event.target.value))} className={inputClass} /></Field><Field label="Window start"><input type="time" value={value.callingWindow.start} onChange={(event) => patch("callingWindow", { ...value.callingWindow, start: event.target.value })} className={inputClass} /></Field><Field label="Window end"><input type="time" value={value.callingWindow.end} onChange={(event) => patch("callingWindow", { ...value.callingWindow, end: event.target.value })} className={inputClass} /></Field></div>
    <SectionTitle title="Campaign-specific conversation" note="The generic agent retains safety and tools; these fields define what this campaign handles." /><div className="grid gap-5"><Field label="Objective"><input value={value.instructions.objective} onChange={(event) => patch("instructions", { ...value.instructions, objective: event.target.value })} className={inputClass} /></Field><Field label="Opening greeting"><textarea rows={3} value={value.instructions.greeting} onChange={(event) => patch("instructions", { ...value.instructions, greeting: event.target.value })} className={textareaClass} /></Field><Field label="Campaign instructions"><textarea rows={7} value={value.instructions.system} onChange={(event) => patch("instructions", { ...value.instructions, system: event.target.value })} className={textareaClass} /></Field><JsonEditor label="Questions / captured fields" value={capture} onChange={setCapture} /></div>
    <div className="mt-5 flex justify-end"><button type="button" onClick={() => void commit()} disabled={busy} className="inline-flex h-11 items-center gap-2 rounded-xl bg-zinc-950 px-5 text-xs font-black text-white">{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />} Save campaign</button></div>
    <SectionTitle title="Daily / monthly outcomes" note="Status counts are aggregated from the unified calls collection." /><div className="mb-3 flex gap-2">{(["day", "month"] as const).map((item) => <button key={item} onClick={() => setPeriod(item)} className={`rounded-lg px-3 py-2 text-[10px] font-black uppercase ${period === item ? "bg-pink-600 text-white" : "bg-pink-50 text-pink-700"}`}>{item}</button>)}</div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{analytics.slice(0, 12).map((item) => <div key={`${item.period}-${item.status}`} className="flex items-center justify-between rounded-xl border border-zinc-100 px-3 py-2 text-xs"><span>{item.period} · {item.status}</span><strong>{item.count}</strong></div>)}{!analytics.length && <p className="text-xs text-zinc-400">No calls in this period yet.</p>}</div>
    <SectionTitle title="Add recipients" note="One per line: +919876543210, external-id, optional name. External ID is the idempotency identity." /><textarea value={targets} onChange={(event) => setTargets(event.target.value)} rows={7} placeholder={"+919876543210, cart-18372, Amon Sharma\n+919811223344, cart-18373, Priya"} className={`${textareaClass} font-mono`} /><div className="mt-4 flex items-center justify-end gap-3">{notice && <p className="mr-auto text-xs text-zinc-600">{notice}</p>}<button type="button" onClick={() => void schedule()} disabled={busy || !targets.trim()} className="inline-flex h-11 items-center gap-2 rounded-xl bg-pink-600 px-5 text-xs font-black text-white disabled:opacity-40">{busy ? <LoaderCircle className="size-4 animate-spin" /> : <ArrowRight className="size-4" />} Schedule idempotently</button></div>
  </section>;
}

function TestCallPanel({ swarms, agents }: { swarms: AgentSwarm[]; agents: AgentConfig[] }) {
  const outbound = swarms.find((item) => item.directions.includes("outbound")); const [swarmId, setSwarmId] = useState(outbound?.id ?? ""); const activeSwarm = swarms.find((item) => item.id === swarmId) ?? outbound; const [agentId, setAgentId] = useState(activeSwarm?.graph.nodes[0]?.agentId ?? ""); const [to, setTo] = useState("+918200962735"); const [name, setName] = useState("Riya Mehta"); const [language, setLanguage] = useState("hi-IN"); const [intent, setIntent] = useState("Recommend a festive outfit under INR 2500"); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  async function submit() { setBusy(true); setNotice(""); try { const result = await triggerTestCall({ swarm_id: swarmId, agent_id: agentId, to_number: to, external_id: `studio-test-${Date.now()}`, idempotency_key: `studio-test-${Date.now()}`, participant: { name }, context: { intent }, metadata: { source: "agent-studio-test", customer_name: name, preferred_language: language } }); setNotice(`Accepted: ${result.call_id}. The call is now visible in All calls.`); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Test call failed."); } finally { setBusy(false); } }
  return <section className="mx-auto max-w-4xl rounded-3xl border border-pink-100 bg-white p-5 sm:p-8"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-pink-600 text-white"><PhoneCall className="size-5" /></span><div><p className="text-[10px] font-black uppercase tracking-[0.14em] text-pink-600">Live SIP smoke test</p><h2 className="mt-1 text-2xl font-black">Call this number to talk with the agent</h2><p className="mt-2 text-xs leading-5 text-zinc-500">Uses the real LiveKit outbound trunk. Keep recipient consent and Twilio India restrictions in mind.</p></div></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Outbound swarm"><select value={swarmId} onChange={(event) => { const next = swarms.find((item) => item.id === event.target.value); setSwarmId(event.target.value); setAgentId(next?.graph.nodes[0]?.agentId ?? ""); }} className={inputClass}>{swarms.filter((item) => item.directions.includes("outbound")).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Starting agent"><select value={agentId} onChange={(event) => setAgentId(event.target.value)} className={inputClass}>{activeSwarm?.graph.nodes.map((node) => <option key={node.key} value={node.agentId}>{node.key} · {agents.find((item) => item.id === node.agentId)?.name ?? node.agentId}</option>)}</select></Field><Field label="Managed caller ID"><ManagedPhoneNumber value={activeSwarm?.telephony.phoneNumber} /></Field><Field label="Call to (E.164)"><input value={to} onChange={(event) => setTo(event.target.value)} className={inputClass} /></Field><Field label="Fabricated shopper name"><input value={name} onChange={(event) => setName(event.target.value)} className={inputClass} /></Field><Field label="Call language"><select value={language} onChange={(event) => setLanguage(event.target.value)} className={inputClass}>{bulbulLanguages.map(([code, label]) => <option key={code} value={code}>{label} · {code}</option>)}</select></Field><Field label="Test intent" wide><textarea rows={4} value={intent} onChange={(event) => setIntent(event.target.value)} className={textareaClass} /></Field></div><div className="mt-6 flex items-center justify-end gap-3">{notice && <p role="status" className="mr-auto text-xs text-zinc-600">{notice}</p>}<button onClick={() => void submit()} disabled={busy || !to || !activeSwarm?.telephony.phoneNumber} className="inline-flex h-11 items-center gap-2 rounded-xl bg-pink-600 px-5 text-xs font-black text-white disabled:opacity-40">{busy ? <LoaderCircle className="size-4 animate-spin" /> : <PhoneCall className="size-4" />} Place test call</button></div></section>;
}

function CredentialsPanel({ credentials, onSaved }: { credentials: ProviderCredentialStatus[]; onSaved: () => Promise<void> }) {
  const [keys, setKeys] = useState<Record<string, string>>({}); const [expiry, setExpiry] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(""); const [notice, setNotice] = useState("");
  async function commit(provider: ProviderCredentialStatus["provider"]) { setBusy(provider); setNotice(""); try { await saveProviderCredential({ provider, label: `${provider} key from Agent Studio`, apiKey: keys[provider] ?? "", expiresAt: expiry[provider] ? new Date(expiry[provider]).toISOString() : null, metadata: { source: "agent-studio" } }); setKeys((current) => ({ ...current, [provider]: "" })); setNotice(`${provider} credential rotated. New calls use Mongo first; environment remains fallback.`); await onSaved(); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Credential save failed."); } finally { setBusy(""); } }
  return <section className="rounded-3xl border border-pink-100 bg-white p-5 sm:p-8"><div className="flex items-start gap-4"><span className="grid size-12 place-items-center rounded-2xl bg-zinc-950 text-white"><ShieldCheck className="size-5" /></span><div><h2 className="text-2xl font-black">Runtime provider credentials</h2><p className="mt-2 max-w-3xl text-xs leading-5 text-zinc-500">Encrypted at rest with AES-GCM. The browser can write a replacement but can never read it back. Active Mongo credentials win; missing or expired credentials fall back to deployment environment variables.</p></div></div>{notice && <p className="mt-5 rounded-xl bg-pink-50 px-4 py-3 text-xs text-pink-800">{notice}</p>}<div className="mt-7 grid gap-4 xl:grid-cols-3">{credentials.map((item) => <div key={item.provider} className="rounded-2xl border border-zinc-100 p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><KeyRound className="size-4 text-pink-600" /><h3 className="font-black capitalize">{item.provider}</h3></div><StatusBadge value={item.configured ? "active" : "missing"} /></div><p className="mt-2 text-[10px] text-zinc-500">Current source: <strong>{item.source}</strong> {item.keyHint ? `· ${item.keyHint}` : ""}</p><Field label="Replace API key"><input type="password" autoComplete="new-password" value={keys[item.provider] ?? ""} onChange={(event) => setKeys((current) => ({ ...current, [item.provider]: event.target.value }))} placeholder="Paste a new key" className={`${inputClass} mt-4`} /></Field><Field label="Optional expiry"><input type="datetime-local" value={expiry[item.provider] ?? ""} onChange={(event) => setExpiry((current) => ({ ...current, [item.provider]: event.target.value }))} className={`${inputClass} mt-3`} /></Field><button onClick={() => void commit(item.provider)} disabled={busy === item.provider || !(keys[item.provider] ?? "").trim()} className="mt-4 inline-flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-zinc-950 text-xs font-black text-white disabled:opacity-40">{busy === item.provider ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />} Rotate securely</button></div>)}</div></section>;
}

function CallsPanel({ calls, totalCount }: { calls: AiCall[]; totalCount: number; agents: AgentConfig[] }) {
  const [items, setItems] = useState(calls); const [page, setPage] = useState(1); const [total, setTotal] = useState(totalCount); const [busy, setBusy] = useState(false); const [expanded, setExpanded] = useState(""); const pageSize = 20;
  async function changePage(nextPage: number) { setBusy(true); try { const result = await getCalls(nextPage, pageSize); setItems(result.items); setTotal(result.total); setPage(nextPage); setExpanded(""); } finally { setBusy(false); } }
  return <section className="overflow-hidden rounded-3xl border border-pink-100 bg-white"><div className="flex items-center justify-between border-b border-pink-100 p-5"><div><h2 className="text-lg font-black">Unified call ledger</h2><p className="text-xs text-zinc-500">Paginated inbound/outbound transcripts, captured answers, post-call disposition, and next action.</p></div><span className="rounded-full bg-pink-50 px-3 py-1 text-xs font-black text-pink-700">{total}</span></div>{items.length ? <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left text-xs"><thead className="bg-zinc-50 text-[10px] uppercase tracking-wider text-zinc-400"><tr><th className="px-5 py-3">Direction</th><th className="px-5 py-3">Contact</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Node</th><th className="px-5 py-3">Disposition / gathered</th><th className="px-5 py-3">Created</th></tr></thead><tbody>{items.map((call) => <FragmentCall key={call.id} call={call} expanded={expanded === call.id} onToggle={() => setExpanded((current) => current === call.id ? "" : call.id)} />)}</tbody></table></div> : <EmptyState title="No calls yet" />}<div className="flex items-center justify-between border-t border-zinc-100 p-4"><button disabled={page === 1 || busy} onClick={() => void changePage(Math.max(1, page - 1))} className="inline-flex items-center gap-1 text-xs font-black disabled:opacity-30"><ArrowLeft className="size-4" /> Previous</button><span className="text-[10px] font-black text-zinc-400">Page {page} of {Math.max(1, Math.ceil(total / pageSize))}</span><button disabled={page * pageSize >= total || busy} onClick={() => void changePage(page + 1)} className="inline-flex items-center gap-1 text-xs font-black disabled:opacity-30">Next <ArrowRight className="size-4" /></button></div></section>;
}

function FragmentCall({ call, expanded, onToggle }: { call: AiCall; expanded: boolean; onToggle: () => void }) { return <><tr onClick={onToggle} className="cursor-pointer border-t border-zinc-100 hover:bg-pink-50/40"><td className="px-5 py-4 font-black capitalize">{call.direction}</td><td className="px-5 py-4 font-mono">{call.direction === "inbound" ? call.from : call.to}</td><td className="px-5 py-4"><StatusBadge value={call.status} /></td><td className="px-5 py-4">{call.currentNodeKey}</td><td className="max-w-sm px-5 py-4 text-zinc-500">{call.disposition?.summary ?? "Pending post-call processing"}</td><td className="px-5 py-4 text-zinc-500">{new Date(call.createdAt).toLocaleString("en-IN")}</td></tr>{expanded && <tr className="bg-zinc-50"><td colSpan={6} className="px-5 py-5"><div className="grid gap-4 lg:grid-cols-2"><div><p className="text-[10px] font-black uppercase tracking-wider text-zinc-400">Captured answers</p><pre className="mt-2 overflow-auto whitespace-pre-wrap rounded-xl bg-white p-3 text-[10px]">{JSON.stringify(call.disposition?.capturedData ?? {}, null, 2)}</pre><p className="mt-3 text-xs"><strong>Next action:</strong> {call.disposition?.nextAction ?? "Pending"}</p></div><div><p className="text-[10px] font-black uppercase tracking-wider text-zinc-400">Transcript</p><div className="mt-2 max-h-56 space-y-2 overflow-y-auto rounded-xl bg-white p-3">{call.transcript?.length ? call.transcript.map((turn, index) => <p key={`${turn.createdAt}-${index}`} className="text-[11px] leading-5"><strong className="capitalize">{turn.role}:</strong> {turn.text}</p>) : <p className="text-[11px] text-zinc-400">Transcript is recorded after the call ends.</p>}</div></div></div></td></tr>}</>; }

function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`block text-[11px] font-black text-zinc-700 ${wide ? "sm:col-span-2" : ""}`}><span className="mb-1.5 block">{label}</span>{children}</label>; }
function SectionTitle({ title, note }: { title: string; note: string }) { return <div className="mb-4 mt-8 border-t border-pink-100 pt-6"><h3 className="text-sm font-black text-zinc-950">{title}</h3><p className="mt-1 text-[11px] text-zinc-500">{note}</p></div>; }
function JsonEditor({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <Field label={label}><div className="relative"><Braces className="absolute right-3 top-3 size-4 text-pink-400" /><textarea value={value} onChange={(event) => onChange(event.target.value)} rows={12} spellCheck={false} className={`${textareaClass} font-mono text-[10px]`} /></div></Field>; }
function StatusBadge({ value }: { value: string }) { const good = ["active", "running", "completed"].includes(value); const bad = ["failed", "cancelled", "archived"].includes(value); return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[9px] font-black uppercase ${good ? "bg-emerald-50 text-emerald-700" : bad ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{good ? <CheckCircle2 className="size-3" /> : bad ? <XCircle className="size-3" /> : null}{value}</span>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl bg-zinc-50 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-zinc-400">{label}</p><p className="mt-2 text-2xl font-black text-zinc-950">{value.toLocaleString("en-IN")}</p></div>; }
function EmptyState({ title }: { title: string }) { return <div className="grid min-h-72 place-items-center rounded-3xl border border-dashed border-pink-200 bg-white p-8 text-center"><div><UsersRound className="mx-auto size-7 text-pink-300" /><p className="mt-3 text-sm font-black">{title}</p></div></div>; }
function ManagedPhoneNumber({ value }: { value?: string }) { const phone = value?.trim() ?? ""; const digits = phone.replace(/\D/g, ""); const display = digits.length === 11 && digits.startsWith("1") ? `+1 ${digits.slice(1, 4)} ${digits.slice(4, 7)} ${digits.slice(7)}` : phone || "Not assigned"; return <div aria-readonly="true" className="flex h-11 items-center justify-between rounded-xl border border-emerald-100 bg-emerald-50 px-3 text-xs font-black text-zinc-900"><span>{display}</span><span className="text-[8px] uppercase text-emerald-700">Read only</span></div>; }
const inputClass = "h-11 w-full rounded-xl border border-zinc-200 bg-white px-3 text-xs font-medium text-zinc-900 outline-none transition focus:border-pink-400 focus:ring-2 focus:ring-pink-100";
const textareaClass = "w-full rounded-xl border border-zinc-200 bg-white px-3 py-3 text-xs leading-5 text-zinc-900 outline-none transition focus:border-pink-400 focus:ring-2 focus:ring-pink-100";
